#DROP TABLE GEA_WEB.CONSOLIDACION_DIARIA;
#CREATE TABLE GEA_WEB.CONSOLIDACION_DIARIA (
#	ID_CONSOLIDACION_DIARIA  INTEGER(10)  NOT NULL AUTO_INCREMENT,
#    /*MEDIDOR_ID INTEGER(10), ELIMINAR ESTO*/
#    NUMERO_DIA INTEGER(8),
#    FECHA DATE,
#    ESTADO INTEGER(1), /* 0.Pendiente, 1.En ProcesoLECTURA_DIARIA, 2.Procesado*/
#    PRIMARY KEY (ID_CONSOLIDACION_DIARIA)
#);
#ALTER TABLE GEA_WEB.CONSOLIDACION_DIARIA ADD CONSTRAINT FK_CON_DIARIA_MEDIDOR FOREIGN KEY (MEDIDOR_ID) REFERENCES GEA_WEB.MEDIDOR (MEDIDOR_ID);
#TODO: add INDEX por fecha

DROP PROCEDURE IF EXISTS GEA_WEB.CONSOLIDACION_DIARIA;
/*
Autor: Marcos Chavarria Fallas
Fecha: 30/05/2019
Revisa las fechas desde el inicio de lectura o desde la última consolidacion generada, y se generan las consolidaciones por día, sin procesar.
*/
DELIMITER //
CREATE PROCEDURE GEA_WEB.CONSOLIDACION_DIARIA()
BEGIN
    /*CONSTANTES*/
    DECLARE C_LIMITE_PROCESO INTEGER(3) DEFAULT 10;
    
    /*VARIABLES*/
	DECLARE V_EN_PROCESO INTEGER(3);
    
    DECLARE V_MEDIDOR_ID INTEGER(10);
    DECLARE V_DIA_NUMERO INTEGER(6);
	DECLARE V_FECHA DATE;
    DECLARE V_CANTIDAD_LECTURA INTEGER(6);
    DECLARE V_MAX_VOLUMEN FLOAT(18,8);
    DECLARE V_MAX_VOLUMEN_CALC FLOAT(18,8);
    DECLARE V_CONSUMO FLOAT(18,8);
    DECLARE V_NO_DATA TINYINT(1) DEFAULT 0;
    DECLARE V_LECTURA_DIARIA_ID INTEGER(10);
	/*CRUSORES*/
    DECLARE CR_LECTURA CURSOR FOR SELECT MEDIDOR_ID, DIA_NUMERO, FECHA, IFNULL(CANTIDAD_LECTURA,0), IFNULL(MAX_VOLUMEN, MAX_VOLUMEN_CALC), MAX_VOLUMEN_CALC FROM V_LECTURA_DIARIA_POR_CONSOLIDAR;
    /*Definicion de Handlers*/
    DECLARE CONTINUE HANDLER FOR NOT FOUND 
        BEGIN 
		SELECT 'NO DATA FOUND';
        SELECT 1 INTO V_NO_DATA;
	END;
    
    #DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    #BEGIN
	#	SELECT 'SE DEPICHO TERE';
        #SELECT CONCAT(@@SQLSTATE_MESSAGE);
    #    ROLLBACK; 
    #END;
    
    SELECT "INICIO SP";
    START TRANSACTION;
	SELECT '1';
    SELECT COUNT(LECTURA_ID) INTO V_EN_PROCESO FROM LECTURA WHERE PROCESADA = 1;
    IF (V_EN_PROCESO = 0) THEN
		SELECT '1.5';
        UPDATE GEA_WEB.LECTURA SET PROCESADA = 1 WHERE PROCESADA = 0 ORDER BY LECTURA_ID LIMIT 10;
	END IF;
    SELECT (LECTURA_ID) INTO V_EN_PROCESO FROM LECTURA WHERE PROCESADA = 1;
    IF (V_EN_PROCESO > 0) THEN
		SELECT '2';
		SELECT 0 INTO V_NO_DATA;
		SELECT '3';
		OPEN CR_LECTURA;
		SELECT '4';
		CUROSOR_LOOP: LOOP
			SELECT '5';
			FETCH CR_LECTURA INTO V_MEDIDOR_ID, V_DIA_NUMERO, V_FECHA, V_CANTIDAD_LECTURA, V_MAX_VOLUMEN, V_MAX_VOLUMEN_CALC;
			IF V_NO_DATA = 1 THEN
				LEAVE CUROSOR_LOOP;
			END IF;
            SELECT '6';
            #REVISA EL REGISTRO DE LECTURA DIARIA, SI NO EXISTE LO CREA, SI EXISTE LO ACTUALIZA
            SELECT IFNULL(LECTURA_DIARIA_ID,0) INTO V_LECTURA_DIARIA_ID FROM LECTURA_DIARIA LD WHERE LD.MEDIDOR_ID = V_MEDIDOR_ID AND DIA_NUMERO = V_DIA_NUMERO;
            IF (V_LECTURA_DIARIA_ID = 0) THEN
				#TODO ADD CONTADOR DE LECTURAS
                INSERT INTO LECTURA_DIARIA (MEDIDOR_ID, MAX_LECTURA, CONSUMO, DIA_NUMERO) VALUES (V_MEDIDOR_ID, V_MAX_VOLUMEN, V_MAX_VOLUMEN - V_MAX_VOLUMEN_CALC, V_DIA_NUMERO);
            ELSE
				UPDATE LECTURA_DIARIA SET MAX_LECTURA = V_MAX_VOLUMEN, CONSUMO = V_MAX_VOLUMEN - V_MAX_VOLUMEN_CALC WHERE LECTURA_DIARIA_ID = V_LECTURA_DIARIA_ID;
            END IF;
			#SELECT CONCAT(V_MEDIDOR_ID,'-');#,V_MAX_VALUMEN,'-',V_DIA_NUMERO);
		END LOOP CUROSOR_LOOP;
		CLOSE CR_LECTURA;
    END IF;
    SELECT "FIN SP";
END //
DELIMITER ;	

#select * from V_LECTURA_DIARIA_POR_CONSOLIDAR
CALL CONSOLIDACION_DIARIA();

  SELECT COUNT(LECTURA_ID) FROM LECTURA WHERE PROCESADA = 1
  
SELECT * FROM LECTURA_DIARIA
SELECT * FROM LECTURA ORDER BY LECTURA_ID;
UPDATE LECTURA SET PROCESADA = 0 

ROLLBACK;
COMMIT;
  